### ISSUE TITLE
Create Docs

### ISSUE THREAD

**Issue by stuartaccent** [AccentDesign/wagtailcolourpicker#3]
like in wagtailstreamforms

**Comment by adamhalesworth** [comment]
How can I help? :+1:

**Comment by stuartaccent** [comment]
Hi @thisdarktao 

We just need to start thinking about writing some docs basically replicating whats done in 
[docs](https://github.com/AccentDesign/wagtailstreamforms/tree/3-dev/docs). Theres no real dev docs just prob:

- Installation
- Basic Usage
- Settings
- Contributors
- Changelog
- Screenshots

Would do to start with. There are things that still need work and testing so its not in a state where it can be published so no rush. You will need a virtualenv and do a 

```
pip install -e .[docs]
```
to install docs dependencies. Then cd docs and in the env

```
sphinx-autobuild . _build
```
then http://127.0.0.1:8000. There is a readme for this in wgtailstreamforms

Ty
