### ISSUE TITLE
Archiving this repo

### ISSUE THREAD

**Issue by stuartaccent** [AccentDesign/wagtailcolourpicker#4]
@thisdarktao, @timaccent, @daveaccent,  Hi guys, I've given this some more thought and am not prepared to publicly support this for the following reasons.

The whole idea of being able to add styles for colours while the site is running goes against every aspect of what happens from when wagtail first starts when pulling in the features into the editor to serving that editor in the form, validating the form when you try to save it, previewing that once you add a colour, and finally serving the page. Nothing helps it on any level. Which makes adding these colours in this way a total hack and will without a doubt cause issues. As I already know there are several outside of the above.

It is not something i want to say to the wider community "Hey look what we've done, it's pants but enjoy the issues you'll have :)".

At best I would be willing to make the colours a fixed list which can be defined up front in the sites settings. This at least we know cannot change while the site is running and design decisions can be left to those in the best place to make them. Meaning all the hacks would be gone too.

I might do this again in another repo and release that leaving this one in a readonly state so it can still be used if we REALLY need to. But I cannot stress enough we shouldn't use it and there will be issues which will be beyond our control.

Whats are your thoughts
Stu

**Comment by daveaccent** [comment]
Yeah I agree, I don't think we should turn Wagtail into WordPress.

**Comment by adamhalesworth** [comment]
If it's not something that fits into the Wagtail functionality smoothly, then forcing this to work would be like trying to push a watermelon through a keyhole. This should go for anything we work on really: if something _can technically_ be done, but leaves a trail of hacks and mess in it's wake, it probably means it _shouldn't_ be done.

**Comment by skip2theend** [comment]
If it goes against Wagtail and becomes hacky; agreed we shouldn't go down that route. Particularly if it we were going to release it and support it.
